### ISSUE TITLE
[com.artillexstudios.axvaults.libs.hikari.pool.ProxyConnection] axvaults-pool - Connection com.mysql.cj.jdbc.ConnectionImpl@52ef11a marked as broken because of SQLSTATE(08S01), ErrorCode(0)

### ISSUE THREAD

**Issue by servicomcr** [Artillex-Studios/AxVaults#10]
[com.artillexstudios.axvaults.libs.hikari.pool.ProxyConnection] axvaults-pool - Connection com.mysql.cj.jdbc.ConnectionImpl@52ef11a marked as broken because of SQLSTATE(08S01), ErrorCode(0)
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
The last packet successfully received from the server was 44 milliseconds ago. The last packet sent successfully to the server was 78 milliseconds ago.
        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:165) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:55) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:938) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1004) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at AxVaults-2.2.1.jar/com.artillexstudios.axvaults.libs.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[AxVaults-2.2.1.jar:?]
        at AxVaults-2.2.1.jar/com.artillexstudios.axvaults.libs.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[AxVaults-2.2.1.jar:?]
        at AxVaults-2.2.1.jar/com.artillexstudios.axvaults.database.impl.MySQL.saveVault(MySQL.java:87) ~[AxVaults-2.2.1.jar:?]
        at AxVaults-2.2.1.jar/com.artillexstudios.axvaults.schedulers.AutoSaveScheduler.lambda$start$0(AutoSaveScheduler.java:28) ~[AxVaults-2.2.1.jar:?]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
The last packet successfully received from the server was 44 milliseconds ago. The last packet sent successfully to the server was 78 milliseconds ago.
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:52) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:95) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:140) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:156) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:597) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:775) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:714) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:946) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.NativeSession.execSQL(NativeSession.java:803) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:915) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        ... 11 more
Caused by: java.net.SocketException: Socket closed
        at java.base/sun.nio.ch.NioSocketImpl.endRead(NioSocketImpl.java:243) ~[?:?]
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323) ~[?:?]
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346) ~[?:?]
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796) ~[?:?]
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099) ~[?:?]
        at com.mysql.cj.protocol.ReadAheadInputStream.fill(ReadAheadInputStream.java:98) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.protocol.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:141) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.protocol.ReadAheadInputStream.read(ReadAheadInputStream.java:171) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:119) ~[?:?]
        at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:55) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.protocol.a.SimplePacketReader.readHeaderLocal(SimplePacketReader.java:72) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:54) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:36) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:43) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:32) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:45) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:35) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:591) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:775) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:714) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:946) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.NativeSession.execSQL(NativeSession.java:803) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:915) ~[mysql-connector-j-8.4.0.jar:8.4.0]
        ... 11 more
[06:51:45 WARN]: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
[06:51:45 WARN]: 
[06:51:45 WARN]: The last packet successfully received from the server was 44 milliseconds ago. The last packet sent successfully to the server was 78 milliseconds ago.
[06:51:45 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:165)
[06:51:45 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:55)
[06:51:45 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:938)
[06:51:45 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1004)
[06:51:45 WARN]:        at AxVaults-2.2.1.jar//com.artillexstudios.axvaults.libs.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
[06:51:45 WARN]:        at AxVaults-2.2.1.jar//com.artillexstudios.axvaults.libs.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
[06:51:45 WARN]:        at AxVaults-2.2.1.jar//com.artillexstudios.axvaults.database.impl.MySQL.saveVault(MySQL.java:87)
[06:51:45 WARN]:        at AxVaults-2.2.1.jar//com.artillexstudios.axvaults.schedulers.AutoSaveScheduler.lambda$start$0(AutoSaveScheduler.java:28)
[06:51:45 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[06:51:45 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
[06:51:45 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[06:51:45 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[06:51:45 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[06:51:45 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[06:51:45 WARN]: Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
[06:51:45 WARN]: 
[06:51:45 WARN]: The last packet successfully received from the server was 44 milliseconds ago. The last packet sent successfully to the server was 78 milliseconds ago.
[06:51:45 WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
[06:51:45 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
[06:51:45 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
[06:51:45 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:52)
[06:51:45 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:95)
[06:51:45 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:140)
[06:51:45 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:156)
[06:51:45 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:597)
[06:51:45 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:775)
[06:51:45 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:714)
[06:51:45 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:946)
[06:51:45 WARN]:        at com.mysql.cj.NativeSession.execSQL(NativeSession.java:803)
[06:51:45 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:915)
[06:51:45 WARN]:        ... 11 more
[06:51:45 WARN]: Caused by: java.net.SocketException: Socket closed
[06:51:45 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.endRead(NioSocketImpl.java:243)
[06:51:45 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
[06:51:45 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
[06:51:45 WARN]:        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
[06:51:45 WARN]:        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099)
[06:51:45 WARN]:        at com.mysql.cj.protocol.ReadAheadInputStream.fill(ReadAheadInputStream.java:98)
[06:51:45 WARN]:        at com.mysql.cj.protocol.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:141)
[06:51:45 WARN]:        at com.mysql.cj.protocol.ReadAheadInputStream.read(ReadAheadInputStream.java:171)
[06:51:45 WARN]:        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:119)
[06:51:45 WARN]:        at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:55)
[06:51:45 WARN]:        at com.mysql.cj.protocol.a.SimplePacketReader.readHeaderLocal(SimplePacketReader.java:72)
[06:51:45 WARN]:        at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:54)
[06:51:45 WARN]:        at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:36)
[06:51:45 WARN]:        at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:43)
[06:51:45 WARN]:        at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:32)
[06:51:45 WARN]:        at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:45)
[06:51:45 WARN]:        at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:35)
[06:51:45 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:591)
[06:51:45 WARN]:        ... 16 more
[06:51:45 WARN]: java.sql.SQLException: HikariDataSource HikariDataSource (axvaults-pool) has been closed.
[06:51:45 WARN]:        at AxVaults-2.2.1.jar//com.artillexstudios.axvaults.libs.hikari.HikariDataSource.getConnection(HikariDataSource.java:95)
[06:51:45 WARN]:        at AxVaults-2.2.1.jar//com.artillexstudios.axvaults.database.impl.MySQL.saveVault(MySQL.java:83)
[06:51:45 WARN]:        at AxVaults-2.2.1.jar//com.artillexstudios.axvaults.schedulers.AutoSaveScheduler.lambda$start$0(AutoSaveScheduler.java:28)
[06:51:45 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[06:51:45 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
[06:51:45 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[06:51:45 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[06:51:45 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[06:51:45 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by BenceX100** [comment]
This seems like a connection issue, which is out of our control.
