### ISSUE TITLE
[com.artillexstudios.axvaults.libs.axapi.data.ThreadedQueue] An unexpected error occurred while running ThreadedQueue AxVaults-Datastore-thread!

### ISSUE THREAD

**Issue by servicomcr** [Artillex-Studios/AxVaults#5]
java.util.ConcurrentModificationException: null
        at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1605) ~[?:?]
        at java.base/java.util.HashMap$ValueIterator.next(HashMap.java:1633) ~[?:?]
        at AxVaults-2.2.0.jar/com.artillexstudios.axvaults.vaults.VaultPlayer.lambda$save$0(VaultPlayer.java:70) ~[AxVaults-2.2.0.jar:?]
        at AxVaults-2.2.0.jar/com.artillexstudios.axvaults.libs.axapi.data.ThreadedQueue.run(ThreadedQueue.java:56) ~[AxVaults-2.2.0.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
        
        
        spigot 1.21

**Comment by BenceX100** [comment]
I belive that this was fixed back in 2.3.0, so I am going to close it.
