### ISSUE TITLE
 An unexpected error occurred while running ThreadedQueue AxVaults-Datastore-thread!

### ISSUE THREAD

**Issue by servicomcr** [Artillex-Studios/AxVaults#8]
[18:09:47 ERROR]: [com.artillexstudios.axvaults.libs.axapi.data.ThreadedQueue] An unexpected error occurred while running ThreadedQueue AxVaults-Datastore-thread!
java.util.ConcurrentModificationException: null
        at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1605) ~[?:?]
        at java.base/java.util.HashMap$ValueIterator.next(HashMap.java:1633) ~[?:?]
        at AxVaults-2.2.1.jar/com.artillexstudios.axvaults.vaults.VaultPlayer.lambda$save$0(VaultPlayer.java:70) ~[AxVaults-2.2.1.jar:?]
        at AxVaults-2.2.1.jar/com.artillexstudios.axvaults.libs.axapi.data.ThreadedQueue.run(ThreadedQueue.java:56) ~[AxVaults-2.2.1.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by BenceX100** [comment]
Should be fixed since 2.3.0, reopen if it still happens
